services:
  agent:
    build: agent
    environment:
      STORAGE_DIRECTORY: ${STORAGE_DIRECTORY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./agent:/app
      - ./glacier:/glacier
    depends_on:
      - storage
    networks:
      - iceberg_net
    restart: no
    read_only: true

  storage:
    image: postgres:16.8
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./storage:/var/lib/postgresql/data
    networks:
      - iceberg_net
    restart: unless-stopped

networks:
  iceberg_net:
    driver: bridge
