services:
  agent:
    build: agent
    environment:
      STORAGE_DIR: ${STORAGE_DIR}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./agent:/app
      - ./glacier:/glacier
    depends_on:
      - storage
    networks:
      - iceberg_net
    restart: no
    read_only: true

  storage:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./storage:/var/lib/postgresql/data
    networks:
      - iceberg_net
    restart: unless-stopped

networks:
  iceberg_net:
    driver: bridge
