services:
  agent:
    build: agent
    environment:
      STORAGE_DIRECTORY: ${STORAGE_DIRECTORY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_COLLECTION: ${DATABASE_COLLECTION}
    volumes:
      - ./glacier:/glacier
      - ./agent:/app
    depends_on:
      - storage
    networks:
      - iceberg_net
    restart: no

  storage:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./storage:/data/db
    networks:
      - iceberg_net
    restart: unless-stopped

networks:
  iceberg_net:
    driver: bridge
