CONNECTING_DB: str = "⏳ Connecting to PostgreSQL"
CONNECTED_DB: str = "✔️ Connected to PostgreSQL for signature storage."
GENERATING_SIGNATURE: str = "⏳ Generating signature for file: {}"
SAVING_SIGNATURE: str = "⏳ Saving signature for {}"
LOADING_SIGNATURE: str = "📥 Loading signature for {}"

STORAGE_DIR_SET: str = "📁 Storage directory set: {}"
SAVING_FILE: str = "⏳ Saving file: {}"
READING_FILE: str = "📥 Reading file: {}"

INIT_COLD_STORAGE: str = "❄️ Glacier initialized and ready."
START_SAVING_FILE: str = "⏳ Starting save process for file: {}"
FILE_SAVED: str = "✔️ File '{}' saved and signature generated."
VERIFYING_FILES: str = "⏳ Verifying all stored files."
NO_SIGNATURE_FOUND: str = "⏳ Saving new signature for '{}'"
FILE_CORRUPTED: str = "❗ File '{}' integrity check invalid"
FILE_VALIDATED: str = "✔️ File '{}' integrity valid"
GENERATING_REPORT: str = "⏳ Generating report..."
REPORT_SUCCESS: str = "✔️ Files verified successfully: {}"
REPORT_FAILURE: str = "❗ Files failed verification: {}"
