CONNECTING_DB: str = "Connecting to PostgreSQL"
CONNECTED_DB: str = "✅ Connected to PostgreSQL for checksum storage."
GENERATING_CHECKSUM: str = "🔧 Generating checksum for file: {}"
SAVING_CHECKSUM: str = "💾 Saving checksum for {}"
LOADING_CHECKSUM: str = "📥 Loading checksum for {}"

STORAGE_DIR_SET: str = "📁 Storage directory set: {}"
SAVING_FILE: str = "💾 Saving file: {}"
READING_FILE: str = "📥 Reading file: {}"

INIT_COLD_STORAGE: str = "❄️ Iceberg initialized and ready."
START_SAVING_FILE: str = "💾 Starting save process for file: {}"
FILE_SAVED: str = "✅ File '{}' saved and checksum generated."
VERIFYING_FILES: str = "🔍 Verifying all stored files."
NO_CHECKSUM_FOUND: str = "⚠️ No checksum found for '{}'. Saving new checksum."
FILE_CORRUPTED: str = "❗ File '{}' is corrupted!"
FILE_VALIDATED: str = "✅ File '{}' is valid"
INTEGRITY_CHECK_FAILED: str = "❗ Integrity check failed for the following files:"
GENERATING_REPORT: str = "📋 Generating report..."
REPORT_SUCCESS: str = "✅ Files verified successfully: {}"
REPORT_FAILURE: str = "❗ Files failed verification: {}"
